tempo:
  reportingEnabled: false

  storage:
    trace:
      backend: local
      local:
        path: /var/tempo/traces

persistence:
  enabled: false

resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 512Mi
    cpu: 300m