grafana:
  enabled: true

  adminUser: admin
  adminPassword: admin

  service:
    type: ClusterIP

  persistence:
    enabled: false

prometheus:
  enabled: true

  prometheusSpec:
    retention: 2d

    resources:
      requests:
        memory: 512Mi
        cpu: 250m
      limits:
        memory: 1Gi
        cpu: 500m

alertmanager:
  enabled: false

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: false